### ISSUE TITLE
Environment variables in commit history

### ISSUE THREAD

**Issue by 0x62** [flickz/jobtweets#2]
You've committed your access tokens by mistake, then removed them but haven't rebased.

https://github.com/flickz/jobtweets/commit/2f0c98b835e8bffb7ab44c295daece6f038932fe

**Comment by flickz** [comment]
Oops! Just remove that. You can fork the dev branch (default). Thanks

**Comment by AkselsLedins** [comment]
@flickz 
`git checkout development`

Just rebase on df3134da7ee91678170e39198cfc46e21fef2c64 :

`git rebase -i df3134da7ee91678170e39198cfc46e21fef2c64`

edit 2f0c98b835e8bffb7ab44c295daece6f038932fe :

![selection_318](https://user-images.githubusercontent.com/18367406/30818244-540b3902-a21b-11e7-943b-04aa4782a03f.png)

exit editor
`git add .env`
`git rebase --continue`
`git push -f`

**Comment by flickz** [comment]
@AkselsLedins  Still not working, here was the result after running `git rebase -i 2f0c98b835e8bffb7ab44c295daece6f038932fe` 

![crop](https://user-images.githubusercontent.com/15707013/30821942-029e305c-a21f-11e7-87e6-4b11b180a012.png)

**Comment by AkselsLedins** [comment]
@flickz 

When you are at this point 

```
git commit --allow-empty
```

and then

```
git rebase --continue
```

______

Before force pushing at the end of the whole procedure (`git push -f`) check briefly if everything seems alright to you

**Comment by flickz** [comment]
After completion, am I still suppose to see the commit with `git show <commit>`?

**Comment by AkselsLedins** [comment]
clone somewhere else your repo and try to `git show <commit>`
your shell should tell you something like this

```
$> git show <commit>
fatal: bad object <commit>
```

I think the commit is somehow cached (but not on the remote)

**But still — change your secretkeys ASAP**


______

Would appreciate someone else thoughts on this, @0x62 ?

**Comment by flickz** [comment]
"But still — change your secretkeys ASAP" @AkselsLedins  Did that immediately @0x62 discovered. Thanks

**Comment by 0x62** [comment]
Since the keys have been revoked it's not massively important, just thought worth mentioning in case they hadn't already been revoked
